version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - .:/var/www/html
    environment:
      SYMFONY_APP_ENV: dev
      DATABASE_URL: postgresql://user:password@db:5432/twitter_db?serverVersion=16
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  db: 
    image: postgres:16
    container_name: twitter_db 
    environment:
      POSTGRES_DB: twitter_db 
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password 
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: