<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260304111516 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE likes DROP CONSTRAINT fk_49ca4e7d458b4eb8');
        $this->addSql('DROP INDEX idx_49ca4e7d458b4eb8');
        $this->addSql('ALTER TABLE likes RENAME COLUMN news_item_id TO tweet_id');
        $this->addSql('ALTER TABLE likes ADD CONSTRAINT FK_49CA4E7D1041E39B FOREIGN KEY (tweet_id) REFERENCES tweet (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_49CA4E7D1041E39B ON likes (tweet_id)');
        $this->addSql('ALTER TABLE news_item DROP CONSTRAINT fk_cac6d395f675f31b');
        $this->addSql('DROP TABLE news_item');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE news_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, is_published BOOLEAN NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, featured_image VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, likes_count INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_cac6d395f675f31b ON news_item (author_id)');
        $this->addSql('ALTER TABLE news_item ADD CONSTRAINT fk_cac6d395f675f31b FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE likes DROP CONSTRAINT FK_49CA4E7D1041E39B');
        $this->addSql('DROP INDEX IDX_49CA4E7D1041E39B');
        $this->addSql('ALTER TABLE likes RENAME COLUMN tweet_id TO news_item_id');
        $this->addSql('ALTER TABLE likes ADD CONSTRAINT fk_49ca4e7d458b4eb8 FOREIGN KEY (news_item_id) REFERENCES news_item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_49ca4e7d458b4eb8 ON likes (news_item_id)');
    }
}
